### PR TITLE
Fix multiple issues, Add notice to Non Javascript Users, Make client not send the secret to the server when viewing pastes

### PR DESCRIPTION
**Pull request by Juliaria08**
Fixing multiples issues at once.

### CODE REVIEW

**Comment by Juliaria08** [comment]
I know I probably should have split the commits up, but I was too lazy to do it afterwards.

**Comment by ComputerTech312** [comment]
I think we should leave out the Jinja template option for now, but the other features seem great. If you could reverse the Jinja template code, but leave the other new features.

**Comment by Juliaria08** [comment]
Ok, I'll later do it.

**Comment by ComputerTech312** [comment]
> Ok, I'll later do it. El 21 de septiembre de 2023 20:44:53 CEST, Colby ***@***.***> escribió:
> […](#)
> I think we should leave out the Jinja template option for now, but the other features seem great. If you could reverse the Jinja template code, but leave the other new features.

Sounds good.

**Comment by Juliaria08** [comment]
I reverted jinja templates.
@ComputerTech312 Do tests again and let's see :)

**Comment by ComputerTech312** [comment]
Tested and accepted.

**Pull request merged**
